version: '3.3'

services:
    api:
        build: ./
        expose:
            - "8000"
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
        restart: always
        volumes:
            - ./:/tmp/
            - ../../src:/app
            - ../../log/api:/var/log/gunicorn
        working_dir: /app
    web:
        depends_on:
            - api
        environment:
            CADDYPATH: /etc/caddycerts
        image: abiosoft/caddy:latest
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "10"
        ports:
            - 80:80
            - 443:443
        restart: always
        volumes:
            - caddy-data:/etc/caddycerts
            - ./caddy/Caddyfile:/etc/Caddyfile
            - ../../log/caddy:/var/log/caddy

volumes:
    caddy-data:
